### ISSUE TITLE
Broken after upgrade to Ubuntu 21.10

### ISSUE THREAD

**Issue by skirsten** [fhunleth/blstrobe#3]
I've been using this awesome tool daily for a few years now but after I upgraded to Ubuntu 21.10 (from 21.04) it just stopped working with this message:

```
$ sudo modprobe i2c-dev
$ sudo blstrobe -g
blstrobe: No displays detected. Make sure that you have run "sudo modprobe i2c-dev" and are calling this as root.
```

Any help is appreciated!

**Comment by fhunleth** [comment]
Oh no!

Thank you for letting me know that the program has been useful to you! I wrote the program and then it turned out that I never used it again after the first month. That was a long time ago and this is bringing back memories. Suffice it to say that I'm probably not going to be much help, but I'll merge pull requests if there are code or documentation changes.

If I were to make a guess, I'd check whether your video card driver changed on the upgrade. Maybe the old one exposed the I2C device and the new one doesn't?

**Comment by skirsten** [comment]
I revisited this and I was able to fix it using https://www.ddcutil.com/nvidia/.
As you noted, something probably changed in the driver.
